// Mocks generated by Mockito 5.4.6 from annotations
// in mona/test/controllers/medication_intake_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mona/data/model/administration_route.dart' as _i13;
import 'package:mona/data/model/date.dart' as _i6;
import 'package:mona/data/model/ester.dart' as _i14;
import 'package:mona/data/model/generic_supply.dart' as _i11;
import 'package:mona/data/model/medication_intake.dart' as _i4;
import 'package:mona/data/model/medication_supply.dart' as _i10;
import 'package:mona/data/model/molecule.dart' as _i12;
import 'package:mona/data/model/supply_item.dart' as _i9;
import 'package:mona/data/providers/medication_intake_provider.dart' as _i3;
import 'package:mona/data/providers/supply_item_provider.dart' as _i8;
import 'package:mona/services/repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRepository_0<T> extends _i1.SmartFake implements _i2.Repository<T> {
  _FakeRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MedicationIntakeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationIntakeProvider extends _i1.Mock
    implements _i3.MedicationIntakeProvider {
  @override
  _i2.Repository<_i4.MedicationIntake> get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRepository_0<_i4.MedicationIntake>(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeRepository_0<_i4.MedicationIntake>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.Repository<_i4.MedicationIntake>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i4.MedicationIntake> get intakes => (super.noSuchMethod(
        Invocation.getter(#intakes),
        returnValue: <_i4.MedicationIntake>[],
        returnValueForMissingStub: <_i4.MedicationIntake>[],
      ) as List<_i4.MedicationIntake>);

  @override
  List<_i4.MedicationIntake> get takenIntakesSortedDesc => (super.noSuchMethod(
        Invocation.getter(#takenIntakesSortedDesc),
        returnValue: <_i4.MedicationIntake>[],
        returnValueForMissingStub: <_i4.MedicationIntake>[],
      ) as List<_i4.MedicationIntake>);

  @override
  List<_i4.MedicationIntake> get takenIntakes => (super.noSuchMethod(
        Invocation.getter(#takenIntakes),
        returnValue: <_i4.MedicationIntake>[],
        returnValueForMissingStub: <_i4.MedicationIntake>[],
      ) as List<_i4.MedicationIntake>);

  @override
  List<_i4.MedicationIntake> get notTakenIntakes => (super.noSuchMethod(
        Invocation.getter(#notTakenIntakes),
        returnValue: <_i4.MedicationIntake>[],
        returnValueForMissingStub: <_i4.MedicationIntake>[],
      ) as List<_i4.MedicationIntake>);

  @override
  List<_i4.MedicationIntake> get graphIntakes => (super.noSuchMethod(
        Invocation.getter(#graphIntakes),
        returnValue: <_i4.MedicationIntake>[],
        returnValueForMissingStub: <_i4.MedicationIntake>[],
      ) as List<_i4.MedicationIntake>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i4.MedicationIntake> getTakenIntakesForSchedule(int? scheduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTakenIntakesForSchedule,
          [scheduleId],
        ),
        returnValue: <_i4.MedicationIntake>[],
        returnValueForMissingStub: <_i4.MedicationIntake>[],
      ) as List<_i4.MedicationIntake>);

  @override
  _i5.Future<void> fetchIntakes() => (super.noSuchMethod(
        Invocation.method(
          #fetchIntakes,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteIntakeFromId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteIntakeFromId,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteIntake(_i4.MedicationIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteIntake,
          [intake],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> add(_i4.MedicationIntake? intake) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [intake],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateIntake(_i4.MedicationIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateIntake,
          [intake],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<int, _i3.GraphIntake> getDaysAndIntakes() => (super.noSuchMethod(
        Invocation.method(
          #getDaysAndIntakes,
          [],
        ),
        returnValue: <int, _i3.GraphIntake>{},
        returnValueForMissingStub: <int, _i3.GraphIntake>{},
      ) as Map<int, _i3.GraphIntake>);

  @override
  _i6.Date? getLastIntakeDateFromList(List<_i4.MedicationIntake>? intakes) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastIntakeDateFromList,
          [intakes],
        ),
        returnValueForMissingStub: null,
      ) as _i6.Date?);

  @override
  _i6.Date? getLastIntakeDateForSchedule(int? scheduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastIntakeDateForSchedule,
          [scheduleId],
        ),
        returnValueForMissingStub: null,
      ) as _i6.Date?);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SupplyItemProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupplyItemProvider extends _i1.Mock
    implements _i8.SupplyItemProvider {
  @override
  _i2.Repository<_i9.SupplyItem> get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRepository_0<_i9.SupplyItem>(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeRepository_0<_i9.SupplyItem>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.Repository<_i9.SupplyItem>);

  @override
  List<_i10.MedicationSupply> get medicationItems => (super.noSuchMethod(
        Invocation.getter(#medicationItems),
        returnValue: <_i10.MedicationSupply>[],
        returnValueForMissingStub: <_i10.MedicationSupply>[],
      ) as List<_i10.MedicationSupply>);

  @override
  List<_i11.GenericSupply> get genericItems => (super.noSuchMethod(
        Invocation.getter(#genericItems),
        returnValue: <_i11.GenericSupply>[],
        returnValueForMissingStub: <_i11.GenericSupply>[],
      ) as List<_i11.GenericSupply>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i10.MedicationSupply> get medicationSuppliesOrderedByRemainingDose =>
      (super.noSuchMethod(
        Invocation.getter(#medicationSuppliesOrderedByRemainingDose),
        returnValue: <_i10.MedicationSupply>[],
        returnValueForMissingStub: <_i10.MedicationSupply>[],
      ) as List<_i10.MedicationSupply>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<void> fetchAll() => (super.noSuchMethod(
        Invocation.method(
          #fetchAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> fetchMedicationItems() => (super.noSuchMethod(
        Invocation.method(
          #fetchMedicationItems,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> fetchGenericItems() => (super.noSuchMethod(
        Invocation.method(
          #fetchGenericItems,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i10.MedicationSupply? getMostUsedItemForMedication(
    _i12.Molecule? molecule,
    _i13.AdministrationRoute? administrationRoute,
    _i14.Ester? ester,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMostUsedItemForMedication,
          [
            molecule,
            administrationRoute,
            ester,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i10.MedicationSupply?);

  @override
  List<_i10.MedicationSupply> getItemsForMedication(
    _i12.Molecule? molecule,
    _i13.AdministrationRoute? administrationRoute,
    _i14.Ester? ester,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsForMedication,
          [
            molecule,
            administrationRoute,
            ester,
          ],
        ),
        returnValue: <_i10.MedicationSupply>[],
        returnValueForMissingStub: <_i10.MedicationSupply>[],
      ) as List<_i10.MedicationSupply>);

  @override
  _i5.Future<void> deleteItemFromId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteItemFromId,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteItem(_i9.SupplyItem? item) => (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [item],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> add(_i9.SupplyItem? medicationSupply) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [medicationSupply],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateItem(_i9.SupplyItem? item) => (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [item],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
