// Mocks generated by Mockito 5.4.6 from annotations
// in mona/test/controllers/notification_scheduler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:flutter/material.dart' as _i12;
import 'package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart'
    as _i13;
import 'package:flutter_local_notifications/src/initialization_settings.dart'
    as _i14;
import 'package:flutter_local_notifications/src/notification_details.dart'
    as _i16;
import 'package:flutter_local_notifications/src/platform_specifics/android/schedule_mode.dart'
    as _i18;
import 'package:flutter_local_notifications/src/types.dart' as _i19;
import 'package:flutter_local_notifications_platform_interface/flutter_local_notifications_platform_interface.dart'
    as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mona/data/model/date.dart' as _i9;
import 'package:mona/data/model/medication_intake.dart' as _i8;
import 'package:mona/data/model/medication_schedule.dart' as _i4;
import 'package:mona/data/model/molecule.dart' as _i11;
import 'package:mona/data/providers/medication_intake_provider.dart' as _i7;
import 'package:mona/data/providers/medication_schedule_provider.dart' as _i3;
import 'package:mona/services/preferences_service.dart' as _i10;
import 'package:mona/services/repository.dart' as _i2;
import 'package:timezone/timezone.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRepository_0<T> extends _i1.SmartFake implements _i2.Repository<T> {
  _FakeRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MedicationScheduleProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationScheduleProvider extends _i1.Mock
    implements _i3.MedicationScheduleProvider {
  @override
  _i2.Repository<_i4.MedicationSchedule> get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRepository_0<_i4.MedicationSchedule>(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeRepository_0<_i4.MedicationSchedule>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.Repository<_i4.MedicationSchedule>);

  @override
  List<_i4.MedicationSchedule> get schedules => (super.noSuchMethod(
        Invocation.getter(#schedules),
        returnValue: <_i4.MedicationSchedule>[],
        returnValueForMissingStub: <_i4.MedicationSchedule>[],
      ) as List<_i4.MedicationSchedule>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.MedicationSchedule? getScheduleById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getScheduleById,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i4.MedicationSchedule?);

  @override
  _i5.Future<void> fetchSchedules() => (super.noSuchMethod(
        Invocation.method(
          #fetchSchedules,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteScheduleFromId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteScheduleFromId,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteSchedule(_i4.MedicationSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSchedule,
          [schedule],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> add(_i4.MedicationSchedule? schedule) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [schedule],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateSchedule(_i4.MedicationSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSchedule,
          [schedule],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MedicationIntakeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationIntakeProvider extends _i1.Mock
    implements _i7.MedicationIntakeProvider {
  @override
  _i2.Repository<_i8.MedicationIntake> get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRepository_0<_i8.MedicationIntake>(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeRepository_0<_i8.MedicationIntake>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.Repository<_i8.MedicationIntake>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i8.MedicationIntake> get intakes => (super.noSuchMethod(
        Invocation.getter(#intakes),
        returnValue: <_i8.MedicationIntake>[],
        returnValueForMissingStub: <_i8.MedicationIntake>[],
      ) as List<_i8.MedicationIntake>);

  @override
  List<_i8.MedicationIntake> get takenIntakesSortedDesc => (super.noSuchMethod(
        Invocation.getter(#takenIntakesSortedDesc),
        returnValue: <_i8.MedicationIntake>[],
        returnValueForMissingStub: <_i8.MedicationIntake>[],
      ) as List<_i8.MedicationIntake>);

  @override
  List<_i8.MedicationIntake> get takenIntakes => (super.noSuchMethod(
        Invocation.getter(#takenIntakes),
        returnValue: <_i8.MedicationIntake>[],
        returnValueForMissingStub: <_i8.MedicationIntake>[],
      ) as List<_i8.MedicationIntake>);

  @override
  List<_i8.MedicationIntake> get notTakenIntakes => (super.noSuchMethod(
        Invocation.getter(#notTakenIntakes),
        returnValue: <_i8.MedicationIntake>[],
        returnValueForMissingStub: <_i8.MedicationIntake>[],
      ) as List<_i8.MedicationIntake>);

  @override
  List<_i8.MedicationIntake> get graphIntakes => (super.noSuchMethod(
        Invocation.getter(#graphIntakes),
        returnValue: <_i8.MedicationIntake>[],
        returnValueForMissingStub: <_i8.MedicationIntake>[],
      ) as List<_i8.MedicationIntake>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i8.MedicationIntake> getTakenIntakesForSchedule(int? scheduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTakenIntakesForSchedule,
          [scheduleId],
        ),
        returnValue: <_i8.MedicationIntake>[],
        returnValueForMissingStub: <_i8.MedicationIntake>[],
      ) as List<_i8.MedicationIntake>);

  @override
  _i5.Future<void> fetchIntakes() => (super.noSuchMethod(
        Invocation.method(
          #fetchIntakes,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteIntakeFromId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteIntakeFromId,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteIntake(_i8.MedicationIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteIntake,
          [intake],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> add(_i8.MedicationIntake? intake) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [intake],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateIntake(_i8.MedicationIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateIntake,
          [intake],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<int, _i7.GraphIntake> getDaysAndIntakes() => (super.noSuchMethod(
        Invocation.method(
          #getDaysAndIntakes,
          [],
        ),
        returnValue: <int, _i7.GraphIntake>{},
        returnValueForMissingStub: <int, _i7.GraphIntake>{},
      ) as Map<int, _i7.GraphIntake>);

  @override
  _i9.Date? getLastIntakeDateFromList(List<_i8.MedicationIntake>? intakes) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastIntakeDateFromList,
          [intakes],
        ),
        returnValueForMissingStub: null,
      ) as _i9.Date?);

  @override
  _i9.Date? getLastIntakeDateForSchedule(int? scheduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastIntakeDateForSchedule,
          [scheduleId],
        ),
        returnValueForMissingStub: null,
      ) as _i9.Date?);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesService extends _i1.Mock
    implements _i10.PreferencesService {
  @override
  bool get autoCheckUpdatesEnabled => (super.noSuchMethod(
        Invocation.getter(#autoCheckUpdatesEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get notificationsEnabled => (super.noSuchMethod(
        Invocation.getter(#notificationsEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i11.Molecule> get customMolecules => (super.noSuchMethod(
        Invocation.getter(#customMolecules),
        returnValue: <_i11.Molecule>[],
        returnValueForMissingStub: <_i11.Molecule>[],
      ) as List<_i11.Molecule>);

  @override
  List<_i11.Molecule> get allMolecules => (super.noSuchMethod(
        Invocation.getter(#allMolecules),
        returnValue: <_i11.Molecule>[],
        returnValueForMissingStub: <_i11.Molecule>[],
      ) as List<_i11.Molecule>);

  @override
  List<_i12.DropdownMenuItem<_i11.Molecule>> get moleculeDropdownItems =>
      (super.noSuchMethod(
        Invocation.getter(#moleculeDropdownItems),
        returnValue: <_i12.DropdownMenuItem<_i11.Molecule>>[],
        returnValueForMissingStub: <_i12.DropdownMenuItem<_i11.Molecule>>[],
      ) as List<_i12.DropdownMenuItem<_i11.Molecule>>);

  @override
  bool get shouldShowScheduleDialog => (super.noSuchMethod(
        Invocation.getter(#shouldShowScheduleDialog),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<void> setAutoCheckUpdatesEnabled(bool? isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAutoCheckUpdatesEnabled,
          [isEnabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setNotificationsEnabled(bool? isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationsEnabled,
          [isEnabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addCustomMolecule(_i11.Molecule? molecule) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCustomMolecule,
          [molecule],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeCustomMolecule(String? name) => (super.noSuchMethod(
        Invocation.method(
          #removeCustomMolecule,
          [name],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setShowScheduleDialog(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setShowScheduleDialog,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i13.FlutterLocalNotificationsPlugin {
  @override
  _i5.Future<bool?> initialize({
    required _i14.InitializationSettings? settings,
    _i15.DidReceiveNotificationResponseCallback?
        onDidReceiveNotificationResponse,
    _i15.DidReceiveBackgroundNotificationResponseCallback?
        onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #settings: settings,
            #onDidReceiveNotificationResponse: onDidReceiveNotificationResponse,
            #onDidReceiveBackgroundNotificationResponse:
                onDidReceiveBackgroundNotificationResponse,
          },
        ),
        returnValue: _i5.Future<bool?>.value(),
        returnValueForMissingStub: _i5.Future<bool?>.value(),
      ) as _i5.Future<bool?>);

  @override
  _i5.Future<_i15.NotificationAppLaunchDetails?>
      getNotificationAppLaunchDetails() => (super.noSuchMethod(
            Invocation.method(
              #getNotificationAppLaunchDetails,
              [],
            ),
            returnValue: _i5.Future<_i15.NotificationAppLaunchDetails?>.value(),
            returnValueForMissingStub:
                _i5.Future<_i15.NotificationAppLaunchDetails?>.value(),
          ) as _i5.Future<_i15.NotificationAppLaunchDetails?>);

  @override
  _i5.Future<void> show({
    required int? id,
    String? title,
    String? body,
    _i16.NotificationDetails? notificationDetails,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #show,
          [],
          {
            #id: id,
            #title: title,
            #body: body,
            #notificationDetails: notificationDetails,
            #payload: payload,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancel({
    required int? id,
    String? tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
          {
            #id: id,
            #tag: tag,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAllPendingNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllPendingNotifications,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> zonedSchedule({
    required int? id,
    required _i17.TZDateTime? scheduledDate,
    required _i16.NotificationDetails? notificationDetails,
    required _i18.AndroidScheduleMode? androidScheduleMode,
    String? title,
    String? body,
    String? payload,
    _i19.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #zonedSchedule,
          [],
          {
            #id: id,
            #scheduledDate: scheduledDate,
            #notificationDetails: notificationDetails,
            #androidScheduleMode: androidScheduleMode,
            #title: title,
            #body: body,
            #payload: payload,
            #matchDateTimeComponents: matchDateTimeComponents,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> periodicallyShow({
    required int? id,
    required _i15.RepeatInterval? repeatInterval,
    required _i16.NotificationDetails? notificationDetails,
    required _i18.AndroidScheduleMode? androidScheduleMode,
    String? title,
    String? body,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShow,
          [],
          {
            #id: id,
            #repeatInterval: repeatInterval,
            #notificationDetails: notificationDetails,
            #androidScheduleMode: androidScheduleMode,
            #title: title,
            #body: body,
            #payload: payload,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> periodicallyShowWithDuration({
    required int? id,
    required Duration? repeatDurationInterval,
    required _i16.NotificationDetails? notificationDetails,
    String? title,
    String? body,
    _i18.AndroidScheduleMode? androidScheduleMode =
        _i18.AndroidScheduleMode.exact,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShowWithDuration,
          [],
          {
            #id: id,
            #repeatDurationInterval: repeatDurationInterval,
            #notificationDetails: notificationDetails,
            #title: title,
            #body: body,
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i15.PendingNotificationRequest>>
      pendingNotificationRequests() => (super.noSuchMethod(
            Invocation.method(
              #pendingNotificationRequests,
              [],
            ),
            returnValue:
                _i5.Future<List<_i15.PendingNotificationRequest>>.value(
                    <_i15.PendingNotificationRequest>[]),
            returnValueForMissingStub:
                _i5.Future<List<_i15.PendingNotificationRequest>>.value(
                    <_i15.PendingNotificationRequest>[]),
          ) as _i5.Future<List<_i15.PendingNotificationRequest>>);

  @override
  _i5.Future<List<_i15.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveNotifications,
          [],
        ),
        returnValue: _i5.Future<List<_i15.ActiveNotification>>.value(
            <_i15.ActiveNotification>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i15.ActiveNotification>>.value(
                <_i15.ActiveNotification>[]),
      ) as _i5.Future<List<_i15.ActiveNotification>>);
}
