// Mocks generated by Mockito 5.4.6 from annotations
// in mona/test/controllers/notification_scheduler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:decimal/decimal.dart' as _i7;
import 'package:flutter/material.dart' as _i3;
import 'package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart'
    as _i10;
import 'package:flutter_local_notifications/src/initialization_settings.dart'
    as _i11;
import 'package:flutter_local_notifications/src/notification_details.dart'
    as _i13;
import 'package:flutter_local_notifications/src/platform_specifics/android/schedule_mode.dart'
    as _i15;
import 'package:flutter_local_notifications/src/types.dart' as _i16;
import 'package:flutter_local_notifications_platform_interface/flutter_local_notifications_platform_interface.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mona/data/model/medication_schedule.dart' as _i5;
import 'package:mona/data/providers/medication_schedule_provider.dart' as _i4;
import 'package:mona/services/preferences_service.dart' as _i9;
import 'package:mona/services/repository.dart' as _i2;
import 'package:timezone/timezone.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRepository_0<T> extends _i1.SmartFake implements _i2.Repository<T> {
  _FakeRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTimeOfDay_1 extends _i1.SmartFake implements _i3.TimeOfDay {
  _FakeTimeOfDay_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MedicationScheduleProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationScheduleProvider extends _i1.Mock
    implements _i4.MedicationScheduleProvider {
  @override
  _i2.Repository<_i5.MedicationSchedule> get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRepository_0<_i5.MedicationSchedule>(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeRepository_0<_i5.MedicationSchedule>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.Repository<_i5.MedicationSchedule>);

  @override
  List<_i5.MedicationSchedule> get schedules => (super.noSuchMethod(
        Invocation.getter(#schedules),
        returnValue: <_i5.MedicationSchedule>[],
        returnValueForMissingStub: <_i5.MedicationSchedule>[],
      ) as List<_i5.MedicationSchedule>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.MedicationSchedule? getScheduleById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getScheduleById,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i5.MedicationSchedule?);

  @override
  _i6.Future<void> fetchSchedules() => (super.noSuchMethod(
        Invocation.method(
          #fetchSchedules,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteScheduleFromId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteScheduleFromId,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteSchedule(_i5.MedicationSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSchedule,
          [schedule],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addSchedule(
    String? name,
    _i7.Decimal? dose,
    int? intervalDays, {
    DateTime? startDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSchedule,
          [
            name,
            dose,
            intervalDays,
          ],
          {#startDate: startDate},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateSchedule(_i5.MedicationSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSchedule,
          [schedule],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesService extends _i1.Mock
    implements _i9.PreferencesService {
  @override
  _i3.TimeOfDay get notificationTime => (super.noSuchMethod(
        Invocation.getter(#notificationTime),
        returnValue: _FakeTimeOfDay_1(
          this,
          Invocation.getter(#notificationTime),
        ),
        returnValueForMissingStub: _FakeTimeOfDay_1(
          this,
          Invocation.getter(#notificationTime),
        ),
      ) as _i3.TimeOfDay);

  @override
  bool get notificationsEnabled => (super.noSuchMethod(
        Invocation.getter(#notificationsEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Future<void> setNotificationHour(int? hour) => (super.noSuchMethod(
        Invocation.method(
          #setNotificationHour,
          [hour],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setNotificationMinute(int? minute) => (super.noSuchMethod(
        Invocation.method(
          #setNotificationMinute,
          [minute],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setNotificationTime(_i3.TimeOfDay? time) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationTime,
          [time],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setNotificationsEnabled(bool? isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationsEnabled,
          [isEnabled],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i10.FlutterLocalNotificationsPlugin {
  @override
  _i6.Future<bool?> initialize(
    _i11.InitializationSettings? initializationSettings, {
    _i12.DidReceiveNotificationResponseCallback?
        onDidReceiveNotificationResponse,
    _i12.DidReceiveBackgroundNotificationResponseCallback?
        onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [initializationSettings],
          {
            #onDidReceiveNotificationResponse: onDidReceiveNotificationResponse,
            #onDidReceiveBackgroundNotificationResponse:
                onDidReceiveBackgroundNotificationResponse,
          },
        ),
        returnValue: _i6.Future<bool?>.value(),
        returnValueForMissingStub: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<_i12.NotificationAppLaunchDetails?>
      getNotificationAppLaunchDetails() => (super.noSuchMethod(
            Invocation.method(
              #getNotificationAppLaunchDetails,
              [],
            ),
            returnValue: _i6.Future<_i12.NotificationAppLaunchDetails?>.value(),
            returnValueForMissingStub:
                _i6.Future<_i12.NotificationAppLaunchDetails?>.value(),
          ) as _i6.Future<_i12.NotificationAppLaunchDetails?>);

  @override
  _i6.Future<void> show(
    int? id,
    String? title,
    String? body,
    _i13.NotificationDetails? notificationDetails, {
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #show,
          [
            id,
            title,
            body,
            notificationDetails,
          ],
          {#payload: payload},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> cancel(
    int? id, {
    String? tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [id],
          {#tag: tag},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> cancelAllPendingNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllPendingNotifications,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> zonedSchedule(
    int? id,
    String? title,
    String? body,
    _i14.TZDateTime? scheduledDate,
    _i13.NotificationDetails? notificationDetails, {
    required _i15.AndroidScheduleMode? androidScheduleMode,
    String? payload,
    _i16.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #zonedSchedule,
          [
            id,
            title,
            body,
            scheduledDate,
            notificationDetails,
          ],
          {
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
            #matchDateTimeComponents: matchDateTimeComponents,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> periodicallyShow(
    int? id,
    String? title,
    String? body,
    _i12.RepeatInterval? repeatInterval,
    _i13.NotificationDetails? notificationDetails, {
    required _i15.AndroidScheduleMode? androidScheduleMode,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShow,
          [
            id,
            title,
            body,
            repeatInterval,
            notificationDetails,
          ],
          {
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> periodicallyShowWithDuration(
    int? id,
    String? title,
    String? body,
    Duration? repeatDurationInterval,
    _i13.NotificationDetails? notificationDetails, {
    _i15.AndroidScheduleMode? androidScheduleMode =
        _i15.AndroidScheduleMode.exact,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShowWithDuration,
          [
            id,
            title,
            body,
            repeatDurationInterval,
            notificationDetails,
          ],
          {
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i12.PendingNotificationRequest>>
      pendingNotificationRequests() => (super.noSuchMethod(
            Invocation.method(
              #pendingNotificationRequests,
              [],
            ),
            returnValue:
                _i6.Future<List<_i12.PendingNotificationRequest>>.value(
                    <_i12.PendingNotificationRequest>[]),
            returnValueForMissingStub:
                _i6.Future<List<_i12.PendingNotificationRequest>>.value(
                    <_i12.PendingNotificationRequest>[]),
          ) as _i6.Future<List<_i12.PendingNotificationRequest>>);

  @override
  _i6.Future<List<_i12.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveNotifications,
          [],
        ),
        returnValue: _i6.Future<List<_i12.ActiveNotification>>.value(
            <_i12.ActiveNotification>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i12.ActiveNotification>>.value(
                <_i12.ActiveNotification>[]),
      ) as _i6.Future<List<_i12.ActiveNotification>>);
}
