// Mocks generated by Mockito 5.4.6 from annotations
// in mona/test/controllers/schedule_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:decimal/decimal.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mona/data/model/medication_intake.dart' as _i9;
import 'package:mona/data/model/medication_schedule.dart' as _i4;
import 'package:mona/data/providers/medication_intake_provider.dart' as _i8;
import 'package:mona/data/providers/medication_schedule_provider.dart' as _i3;
import 'package:mona/services/repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRepository_0<T> extends _i1.SmartFake implements _i2.Repository<T> {
  _FakeRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MedicationScheduleProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationScheduleProvider extends _i1.Mock
    implements _i3.MedicationScheduleProvider {
  @override
  _i2.Repository<_i4.MedicationSchedule> get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRepository_0<_i4.MedicationSchedule>(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeRepository_0<_i4.MedicationSchedule>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.Repository<_i4.MedicationSchedule>);

  @override
  List<_i4.MedicationSchedule> get schedules => (super.noSuchMethod(
        Invocation.getter(#schedules),
        returnValue: <_i4.MedicationSchedule>[],
        returnValueForMissingStub: <_i4.MedicationSchedule>[],
      ) as List<_i4.MedicationSchedule>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.MedicationSchedule? getScheduleById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getScheduleById,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i4.MedicationSchedule?);

  @override
  _i5.Future<void> fetchSchedules() => (super.noSuchMethod(
        Invocation.method(
          #fetchSchedules,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteScheduleFromId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteScheduleFromId,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteSchedule(_i4.MedicationSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSchedule,
          [schedule],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addSchedule(
    String? name,
    _i6.Decimal? dose,
    int? intervalDays, {
    DateTime? startDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSchedule,
          [
            name,
            dose,
            intervalDays,
          ],
          {#startDate: startDate},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateSchedule(_i4.MedicationSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSchedule,
          [schedule],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MedicationIntakeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationIntakeProvider extends _i1.Mock
    implements _i8.MedicationIntakeProvider {
  @override
  _i2.Repository<_i9.MedicationIntake> get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRepository_0<_i9.MedicationIntake>(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeRepository_0<_i9.MedicationIntake>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.Repository<_i9.MedicationIntake>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i9.MedicationIntake> get intakes => (super.noSuchMethod(
        Invocation.getter(#intakes),
        returnValue: <_i9.MedicationIntake>[],
        returnValueForMissingStub: <_i9.MedicationIntake>[],
      ) as List<_i9.MedicationIntake>);

  @override
  List<_i9.MedicationIntake> get takenIntakesSortedDesc => (super.noSuchMethod(
        Invocation.getter(#takenIntakesSortedDesc),
        returnValue: <_i9.MedicationIntake>[],
        returnValueForMissingStub: <_i9.MedicationIntake>[],
      ) as List<_i9.MedicationIntake>);

  @override
  List<_i9.MedicationIntake> get takenIntakes => (super.noSuchMethod(
        Invocation.getter(#takenIntakes),
        returnValue: <_i9.MedicationIntake>[],
        returnValueForMissingStub: <_i9.MedicationIntake>[],
      ) as List<_i9.MedicationIntake>);

  @override
  List<_i9.MedicationIntake> get notTakenIntakes => (super.noSuchMethod(
        Invocation.getter(#notTakenIntakes),
        returnValue: <_i9.MedicationIntake>[],
        returnValueForMissingStub: <_i9.MedicationIntake>[],
      ) as List<_i9.MedicationIntake>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i9.MedicationIntake> getTakenIntakesForSchedule(int? scheduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTakenIntakesForSchedule,
          [scheduleId],
        ),
        returnValue: <_i9.MedicationIntake>[],
        returnValueForMissingStub: <_i9.MedicationIntake>[],
      ) as List<_i9.MedicationIntake>);

  @override
  _i5.Future<void> fetchIntakes() => (super.noSuchMethod(
        Invocation.method(
          #fetchIntakes,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteIntakeFromId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteIntakeFromId,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteIntake(_i9.MedicationIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteIntake,
          [intake],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addIntake(
    DateTime? scheduledDateTime,
    _i6.Decimal? dose,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addIntake,
          [
            scheduledDateTime,
            dose,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> add(_i9.MedicationIntake? intake) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [intake],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateIntake(_i9.MedicationIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateIntake,
          [intake],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<int, double> getDaysAndDoses() => (super.noSuchMethod(
        Invocation.method(
          #getDaysAndDoses,
          [],
        ),
        returnValue: <int, double>{},
        returnValueForMissingStub: <int, double>{},
      ) as Map<int, double>);

  @override
  DateTime? getLastIntakeDateFromList(List<_i9.MedicationIntake>? intakes) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastIntakeDateFromList,
          [intakes],
        ),
        returnValueForMissingStub: null,
      ) as DateTime?);

  @override
  DateTime? getLastIntakeDateForSchedule(int? scheduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastIntakeDateForSchedule,
          [scheduleId],
        ),
        returnValueForMissingStub: null,
      ) as DateTime?);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
