// Mocks generated by Mockito 5.4.6 from annotations
// in mona/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i9;

import 'package:decimal/decimal.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mona/controllers/supply_item_manager.dart' as _i14;
import 'package:mona/data/model/administration_route.dart' as _i7;
import 'package:mona/data/model/ester.dart' as _i8;
import 'package:mona/data/model/medication_intake.dart' as _i11;
import 'package:mona/data/model/medication_schedule.dart' as _i13;
import 'package:mona/data/model/molecule.dart' as _i6;
import 'package:mona/data/model/supply_item.dart' as _i4;
import 'package:mona/data/providers/medication_intake_provider.dart' as _i10;
import 'package:mona/data/providers/medication_schedule_provider.dart' as _i12;
import 'package:mona/data/providers/supply_item_provider.dart' as _i3;
import 'package:mona/services/repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRepository_0<T> extends _i1.SmartFake implements _i2.Repository<T> {
  _FakeRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SupplyItemProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupplyItemProvider extends _i1.Mock
    implements _i3.SupplyItemProvider {
  MockSupplyItemProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Repository<_i4.SupplyItem> get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRepository_0<_i4.SupplyItem>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.Repository<_i4.SupplyItem>);

  @override
  List<_i4.SupplyItem> get items => (super.noSuchMethod(
        Invocation.getter(#items),
        returnValue: <_i4.SupplyItem>[],
      ) as List<_i4.SupplyItem>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  List<_i4.SupplyItem> get orderedByRemainingDose => (super.noSuchMethod(
        Invocation.getter(#orderedByRemainingDose),
        returnValue: <_i4.SupplyItem>[],
      ) as List<_i4.SupplyItem>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> fetchItems() => (super.noSuchMethod(
        Invocation.method(
          #fetchItems,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i4.SupplyItem? getMostUsedItemForMedication(
    _i6.Molecule? molecule,
    _i7.AdministrationRoute? administrationRoute,
    _i8.Ester? ester,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getMostUsedItemForMedication,
        [
          molecule,
          administrationRoute,
          ester,
        ],
      )) as _i4.SupplyItem?);

  @override
  List<_i4.SupplyItem> getItemsForMedication(
    _i6.Molecule? molecule,
    _i7.AdministrationRoute? administrationRoute,
    _i8.Ester? ester,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsForMedication,
          [
            molecule,
            administrationRoute,
            ester,
          ],
        ),
        returnValue: <_i4.SupplyItem>[],
      ) as List<_i4.SupplyItem>);

  @override
  _i5.Future<void> deleteItemFromId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteItemFromId,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteItem(_i4.SupplyItem? item) => (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [item],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> add(_i4.SupplyItem? supplyItem) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [supplyItem],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateItem(_i4.SupplyItem? item) => (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [item],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MedicationIntakeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationIntakeProvider extends _i1.Mock
    implements _i10.MedicationIntakeProvider {
  MockMedicationIntakeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Repository<_i11.MedicationIntake> get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRepository_0<_i11.MedicationIntake>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.Repository<_i11.MedicationIntake>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  List<_i11.MedicationIntake> get intakes => (super.noSuchMethod(
        Invocation.getter(#intakes),
        returnValue: <_i11.MedicationIntake>[],
      ) as List<_i11.MedicationIntake>);

  @override
  List<_i11.MedicationIntake> get takenIntakesSortedDesc => (super.noSuchMethod(
        Invocation.getter(#takenIntakesSortedDesc),
        returnValue: <_i11.MedicationIntake>[],
      ) as List<_i11.MedicationIntake>);

  @override
  List<_i11.MedicationIntake> get takenIntakes => (super.noSuchMethod(
        Invocation.getter(#takenIntakes),
        returnValue: <_i11.MedicationIntake>[],
      ) as List<_i11.MedicationIntake>);

  @override
  List<_i11.MedicationIntake> get notTakenIntakes => (super.noSuchMethod(
        Invocation.getter(#notTakenIntakes),
        returnValue: <_i11.MedicationIntake>[],
      ) as List<_i11.MedicationIntake>);

  @override
  List<_i11.MedicationIntake> get graphIntakes => (super.noSuchMethod(
        Invocation.getter(#graphIntakes),
        returnValue: <_i11.MedicationIntake>[],
      ) as List<_i11.MedicationIntake>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  List<_i11.MedicationIntake> getTakenIntakesForSchedule(int? scheduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTakenIntakesForSchedule,
          [scheduleId],
        ),
        returnValue: <_i11.MedicationIntake>[],
      ) as List<_i11.MedicationIntake>);

  @override
  _i5.Future<void> fetchIntakes() => (super.noSuchMethod(
        Invocation.method(
          #fetchIntakes,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteIntakeFromId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteIntakeFromId,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteIntake(_i11.MedicationIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteIntake,
          [intake],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> add(_i11.MedicationIntake? intake) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [intake],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateIntake(_i11.MedicationIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateIntake,
          [intake],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<int, _i10.GraphIntake> getDaysAndIntakes() => (super.noSuchMethod(
        Invocation.method(
          #getDaysAndIntakes,
          [],
        ),
        returnValue: <int, _i10.GraphIntake>{},
      ) as Map<int, _i10.GraphIntake>);

  @override
  DateTime? getLastIntakeDateFromList(List<_i11.MedicationIntake>? intakes) =>
      (super.noSuchMethod(Invocation.method(
        #getLastIntakeDateFromList,
        [intakes],
      )) as DateTime?);

  @override
  DateTime? getLastIntakeDateForSchedule(int? scheduleId) =>
      (super.noSuchMethod(Invocation.method(
        #getLastIntakeDateForSchedule,
        [scheduleId],
      )) as DateTime?);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MedicationScheduleProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationScheduleProvider extends _i1.Mock
    implements _i12.MedicationScheduleProvider {
  MockMedicationScheduleProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Repository<_i13.MedicationSchedule> get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRepository_0<_i13.MedicationSchedule>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.Repository<_i13.MedicationSchedule>);

  @override
  List<_i13.MedicationSchedule> get schedules => (super.noSuchMethod(
        Invocation.getter(#schedules),
        returnValue: <_i13.MedicationSchedule>[],
      ) as List<_i13.MedicationSchedule>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i13.MedicationSchedule? getScheduleById(int? id) =>
      (super.noSuchMethod(Invocation.method(
        #getScheduleById,
        [id],
      )) as _i13.MedicationSchedule?);

  @override
  _i5.Future<void> fetchSchedules() => (super.noSuchMethod(
        Invocation.method(
          #fetchSchedules,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteScheduleFromId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteScheduleFromId,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteSchedule(_i13.MedicationSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSchedule,
          [schedule],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> add(_i13.MedicationSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [schedule],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateSchedule(_i13.MedicationSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSchedule,
          [schedule],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SupplyItemManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupplyItemManager extends _i1.Mock implements _i14.SupplyItemManager {
  MockSupplyItemManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> useDose(
    _i4.SupplyItem? item,
    _i15.Decimal? doseToUse,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #useDose,
          [
            item,
            doseToUse,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
