// Mocks generated by Mockito 5.4.4 from annotations
// in transdiy/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:decimal/decimal.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:transdiy/controllers/supply_item_manager.dart' as _i10;
import 'package:transdiy/data/model/medication_intake.dart' as _i9;
import 'package:transdiy/data/model/supply_item.dart' as _i3;
import 'package:transdiy/data/providers/medication_intake_provider.dart' as _i8;
import 'package:transdiy/data/providers/supply_item_provider.dart' as _i4;
import 'package:transdiy/services/generic_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGenericRepository_0<T> extends _i1.SmartFake
    implements _i2.GenericRepository<T> {
  _FakeGenericRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupplyItem_1 extends _i1.SmartFake implements _i3.SupplyItem {
  _FakeSupplyItem_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SupplyItemProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupplyItemProvider extends _i1.Mock
    implements _i4.SupplyItemProvider {
  MockSupplyItemProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GenericRepository<_i3.SupplyItem> get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGenericRepository_0<_i3.SupplyItem>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.GenericRepository<_i3.SupplyItem>);

  @override
  set repository(_i2.GenericRepository<_i3.SupplyItem>? _repository) =>
      super.noSuchMethod(
        Invocation.setter(
          #repository,
          _repository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i3.SupplyItem> get items => (super.noSuchMethod(
        Invocation.getter(#items),
        returnValue: <_i3.SupplyItem>[],
      ) as List<_i3.SupplyItem>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> fetchItems() => (super.noSuchMethod(
        Invocation.method(
          #fetchItems,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteItemFromId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteItemFromId,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteItem(_i3.SupplyItem? item) => (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [item],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addItem(
    _i6.Decimal? totalDose,
    String? name,
    _i6.Decimal? dosePerUnit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addItem,
          [
            totalDose,
            name,
            dosePerUnit,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateItem(_i3.SupplyItem? item) => (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [item],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MedicationIntakeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationIntakeProvider extends _i1.Mock
    implements _i8.MedicationIntakeProvider {
  MockMedicationIntakeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GenericRepository<_i9.MedicationIntake> get repository =>
      (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGenericRepository_0<_i9.MedicationIntake>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.GenericRepository<_i9.MedicationIntake>);

  @override
  List<_i9.MedicationIntake> get intakes => (super.noSuchMethod(
        Invocation.getter(#intakes),
        returnValue: <_i9.MedicationIntake>[],
      ) as List<_i9.MedicationIntake>);

  @override
  List<_i9.MedicationIntake> get takenIntakes => (super.noSuchMethod(
        Invocation.getter(#takenIntakes),
        returnValue: <_i9.MedicationIntake>[],
      ) as List<_i9.MedicationIntake>);

  @override
  List<_i9.MedicationIntake> get notTakenIntakes => (super.noSuchMethod(
        Invocation.getter(#notTakenIntakes),
        returnValue: <_i9.MedicationIntake>[],
      ) as List<_i9.MedicationIntake>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> fetchIntakes() => (super.noSuchMethod(
        Invocation.method(
          #fetchIntakes,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteIntakeFromId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteIntakeFromId,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteIntake(_i9.MedicationIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteIntake,
          [intake],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addIntake(
    DateTime? scheduledDateTime,
    _i6.Decimal? dose,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addIntake,
          [
            scheduledDateTime,
            dose,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateIntake(_i9.MedicationIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateIntake,
          [intake],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SupplyItemManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupplyItemManager extends _i1.Mock implements _i10.SupplyItemManager {
  MockSupplyItemManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.SupplyItem> setFields(
    _i3.SupplyItem? item, {
    String? newName,
    _i6.Decimal? newTotalDose,
    _i6.Decimal? newUsedDose,
    _i6.Decimal? newDosePerUnit,
    int? newQuantity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFields,
          [item],
          {
            #newName: newName,
            #newTotalDose: newTotalDose,
            #newUsedDose: newUsedDose,
            #newDosePerUnit: newDosePerUnit,
            #newQuantity: newQuantity,
          },
        ),
        returnValue: _i5.Future<_i3.SupplyItem>.value(_FakeSupplyItem_1(
          this,
          Invocation.method(
            #setFields,
            [item],
            {
              #newName: newName,
              #newTotalDose: newTotalDose,
              #newUsedDose: newUsedDose,
              #newDosePerUnit: newDosePerUnit,
              #newQuantity: newQuantity,
            },
          ),
        )),
      ) as _i5.Future<_i3.SupplyItem>);

  @override
  _i5.Future<void> useDose(
    _i3.SupplyItem? item,
    _i6.Decimal? doseToUse,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #useDose,
          [
            item,
            doseToUse,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
